# Extension service

Services:
  - Type: Extension
    Name: database
    Instance: w3-storage-01
    Controllers:
      # Extension service's controller type and name are omitted
      # They are called "main"
      - Type: Replier
        Name: main
        Instances:
          - Port: 8002
            Instance: ""
    # Proxies are omitted, this extension doesn't depend on the proxies
    # Proxy pipelines. If it's not given then the proxies won't be used.
    # The last node in the path should be the ControllerName or ServiceName
    # Pipelines:
    #  - "auth->validator->userApi"
    # Extensions are omitted, this extension doesn't depend on other extensions